# KWS: TFLite Micro + Audio Preprocessor
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_REQUIRES_FLOAT_PRINTF=y

# Disable networking (not needed)
CONFIG_NETWORKING=n
