CONFIG_ENTROPY_STM32_RNG=y
CONFIG_ENTROPY_GENERATOR=y
# CONFIG_ENTROPY_DEVICE_RANDOM_GENERATOR=y
CONFIG_DEBUG=y
# CONFIG_ASSERT=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_LOG_MODE_MINIMAL=y
CONFIG_SDHC=y
# CONFIG_SD_BUFFER_SIZE=64
CONFIG_SDMMC_STM32=y
 
CONFIG_CLOCK_CONTROL=y
CONFIG_MAIN_STACK_SIZE=4096  
 
CONFIG_PM=y
# CONFIG_SDHC_STM32_DMA=y
 
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_SDMMC_STACK=y
CONFIG_WIFI=y
# CONFIG_ST_STM32_SDMMC=y
# CONFIG_SIZE_OPTIMIZATIONS=y
 
# CONFIG_MAIN_STACK_SIZE=2048
# CONFIG_IDLE_STACK_SIZE=512
# CONFIG_ISR_STACK_SIZE=1024CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
 
 
# CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
 
CONFIG_HEAP_MEM_POOL_SIZE=4096
 
 
CONFIG_WIFI=y
 
 
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y
 